-v09: Spice things up by adding the SendMsg action, which introduces the case that an inactive node reactivates.
```tla
Error: Invariant Inv is violated.
Error: The behavior up to this point is:
State 1: <Initial predicate>
/\ tpos = 0
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> TRUE @@ 4 :> FALSE)
/\ tcolor = FALSE

State 2: <InitiateProbe line 22, col 3 to line 26, col 25 of module EWD840>
/\ tpos = 4
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> TRUE @@ 4 :> FALSE)
/\ tcolor = TRUE

State 3: <PassToken line 29, col 5 to line 32, col 35 of module EWD840>
/\ tpos = 3
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> TRUE @@ 4 :> FALSE)
/\ tcolor = TRUE

State 4: <SendMsg line 44, col 5 to line 47, col 33 of module EWD840>
/\ tpos = 3
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> TRUE @@ 4 :> TRUE)
/\ tcolor = TRUE

State 5: <Deactivate line 39, col 5 to line 41, col 33 of module EWD840>
/\ tpos = 3
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> TRUE)
/\ tcolor = TRUE

State 6: <PassToken line 29, col 5 to line 32, col 35 of module EWD840>
/\ tpos = 2
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> TRUE)
/\ tcolor = TRUE

State 7: <PassToken line 29, col 5 to line 32, col 35 of module EWD840>
/\ tpos = 1
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> TRUE)
/\ tcolor = TRUE

State 8: <PassToken line 29, col 5 to line 32, col 35 of module EWD840>
/\ tpos = 0
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> TRUE)
/\ tcolor = TRUE
```