-v04: Add liveness property that asserts that termination is detected after all nodes have terminated.
This property is immediately violated by the current behavior spec,
because the spec lacks a fairness constraint.

```tla
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
/\ tpos = 0
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> FALSE)
/\ tcolor = FALSE

State 2: <InitiateProbe line 22, col 3 to line 26, col 25 of module EWD840>
/\ tpos = 4
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> FALSE)
/\ tcolor = TRUE

State 3: <PassToken line 29, col 5 to line 32, col 35 of module EWD840>
/\ tpos = 3
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> FALSE)
/\ tcolor = TRUE

State 4: <PassToken line 29, col 5 to line 32, col 35 of module EWD840>
/\ tpos = 2
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> FALSE)
/\ tcolor = TRUE

State 5: <PassToken line 29, col 5 to line 32, col 35 of module EWD840>
/\ tpos = 1
/\ active = (0 :> FALSE @@ 1 :> FALSE @@ 2 :> FALSE @@ 3 :> FALSE @@ 4 :> FALSE)
/\ tcolor = TRUE

State 6: Stuttering
```